"""initial schema

Revision ID: a24b85aac576
Revises: 
Create Date: 2026-09-07 22:15:49.820687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a24b85aac576'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anamnesis_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('prompt', sa.String(length=300), nullable=False),
    sa.Column('help_text', sa.String(length=300), nullable=True),
    sa.Column('answer_type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('risk_factor_code', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('pathway_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_text', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pathway_template_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('metric_code', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['pathway_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('fiscal_code', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('primary_diagnosis', sa.String(length=120), nullable=True),
    sa.Column('comorbidities', sa.Text(), nullable=True),
    sa.Column('employer', sa.String(length=120), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('work_pattern', sa.String(length=40), nullable=True),
    sa.Column('assigned_doctor_id', sa.Integer(), nullable=True),
    sa.Column('enrolled_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('anamnesis_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=300), nullable=False),
    sa.Column('answered_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['anamnesis_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'question_id', name='uq_answer_patient_question')
    )
    op.create_index(op.f('ix_anamnesis_answers_patient_id'), 'anamnesis_answers', ['patient_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_via', sa.String(length=20), nullable=False),
    sa.Column('triage_assessment_id', sa.Integer(), nullable=True),
    sa.Column('pathway_step_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('care_pathways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['pathway_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_pathways_patient_id'), 'care_pathways', ['patient_id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_patient_id'), 'chat_threads', ['patient_id'], unique=False)
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('facility', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('controllo','urgenza','followup')", name='ck_encounter_kind'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_patient_id'), 'follow_ups', ['patient_id'], unique=False)
    op.create_table('health_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('frequency_per_week', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_goals_patient_id'), 'health_goals', ['patient_id'], unique=False)
    op.create_table('monitoring_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('target_text', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_plan_items_patient_id'), 'monitoring_plan_items', ['patient_id'], unique=False)
    op.create_table('patient_medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('dosage', sa.String(length=120), nullable=True),
    sa.Column('schedule', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_medications_patient_id'), 'patient_medications', ['patient_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('risk_count', sa.Integer(), nullable=False),
    sa.Column('protective_count', sa.Integer(), nullable=False),
    sa.Column('components', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_patient_id'), 'risk_assessments', ['patient_id'], unique=False)
    op.create_table('wellbeing_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=30), nullable=False),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellbeing_assessments_patient_id'), 'wellbeing_assessments', ['patient_id'], unique=False)
    op.create_table('anamnesis_answer_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.String(length=300), nullable=True),
    sa.Column('new_value', sa.String(length=300), nullable=False),
    sa.Column('answered_by', sa.String(length=10), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['anamnesis_answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['anamnesis_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anamnesis_answer_history_answer_id'), 'anamnesis_answer_history', ['answer_id'], unique=False)
    op.create_index(op.f('ix_anamnesis_answer_history_patient_id'), 'anamnesis_answer_history', ['patient_id'], unique=False)
    op.create_table('care_pathway_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pathway_id', sa.Integer(), nullable=False),
    sa.Column('template_step_code', sa.String(length=50), nullable=True),
    sa.Column('metric_code', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('followup_id', sa.Integer(), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['followup_id'], ['follow_ups.id'], ),
    sa.ForeignKeyConstraint(['pathway_id'], ['care_pathways.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_pathway_steps_pathway_id'), 'care_pathway_steps', ['pathway_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=12), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('goal_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('completed_days', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['health_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("source IN ('lab','clinic','patient_home')", name='ck_observation_source'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_obs_patient_code_date', 'observations', ['patient_id', 'code', 'taken_on'], unique=False)
    op.create_index(op.f('ix_observations_patient_id'), 'observations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_observations_taken_on'), 'observations', ['taken_on'], unique=False)
    op.create_table('triage_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('operator_user_id', sa.Integer(), nullable=False),
    sa.Column('protocol_code', sa.String(length=40), nullable=False),
    sa.Column('complaint_label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('tier', sa.String(length=12), nullable=False),
    sa.Column('disposition_code', sa.String(length=30), nullable=False),
    sa.Column('disposition_label', sa.String(length=200), nullable=False),
    sa.Column('disposition_detail', sa.Text(), nullable=True),
    sa.Column('red_flags', sa.Text(), nullable=True),
    sa.Column('risk_level_at_triage', sa.String(length=10), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('followup_id', sa.Integer(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['followup_id'], ['follow_ups.id'], ),
    sa.ForeignKeyConstraint(['operator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_assessments_created_at'), 'triage_assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_triage_assessments_patient_id'), 'triage_assessments', ['patient_id'], unique=False)

    # Runtime data the application depends on: anamnesis catalogue + pathway
    # templates (same content the services seed at startup).
    import json as _json
    import sys as _sys
    from datetime import datetime as _datetime, timezone as _timezone
    from pathlib import Path as _Path

    _sys.path.insert(0, str(_Path(__file__).resolve().parents[2]))
    from services.anamnesis import DEFAULT_QUESTIONS as _QUESTIONS
    from services.pathways import TEMPLATES as _TEMPLATES

    _bind = op.get_bind()
    _now = _datetime.now(_timezone.utc)

    _q = sa.table(
        "anamnesis_questions",
        sa.column("code"), sa.column("section"), sa.column("prompt"),
        sa.column("help_text"), sa.column("answer_type"), sa.column("options"),
        sa.column("order"), sa.column("risk_factor_code"), sa.column("active"),
        sa.column("updated_at"),
    )
    for _spec in _QUESTIONS:
        _bind.execute(_q.insert().values(
            code=_spec["code"], section=_spec["section"], prompt=_spec["prompt"],
            help_text=_spec.get("help_text"),
            answer_type=_spec.get("answer_type", "single_choice"),
            options=_json.dumps(_spec.get("options", [])),
            order=_spec["order"], risk_factor_code=_spec["code"], active=True,
            updated_at=_now,
        ))

    _t = sa.table(
        "pathway_templates",
        sa.column("code"), sa.column("name"),
        sa.column("description"), sa.column("target_text"), sa.column("active"),
    )
    _ts = sa.table(
        "pathway_template_steps",
        sa.column("template_id"), sa.column("code"), sa.column("title"),
        sa.column("description"), sa.column("kind"), sa.column("offset_days"),
        sa.column("step_order"), sa.column("metric_code"),
    )
    for _spec in _TEMPLATES:
        _bind.execute(_t.insert().values(
            code=_spec["code"], name=_spec["name"], description=_spec["description"],
            target_text=_spec["target_text"], active=True,
        ))
        template_id = _bind.execute(
            sa.text("SELECT id FROM pathway_templates WHERE code = :c"),
            {"c": _spec["code"]},
        ).scalar()
        for (_code, _title, _desc, _kind, _offset, _order, _metric) in _spec["steps"]:
            _bind.execute(_ts.insert().values(
                template_id=template_id, code=_code, title=_title,
                description=_desc, kind=_kind, offset_days=_offset,
                step_order=_order, metric_code=_metric,
            ))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_assessments_patient_id'), table_name='triage_assessments')
    op.drop_index(op.f('ix_triage_assessments_created_at'), table_name='triage_assessments')
    op.drop_table('triage_assessments')
    op.drop_index(op.f('ix_observations_taken_on'), table_name='observations')
    op.drop_index(op.f('ix_observations_patient_id'), table_name='observations')
    op.drop_index('ix_obs_patient_code_date', table_name='observations')
    op.drop_table('observations')
    op.drop_table('goal_checkins')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_care_pathway_steps_pathway_id'), table_name='care_pathway_steps')
    op.drop_table('care_pathway_steps')
    op.drop_index(op.f('ix_anamnesis_answer_history_patient_id'), table_name='anamnesis_answer_history')
    op.drop_index(op.f('ix_anamnesis_answer_history_answer_id'), table_name='anamnesis_answer_history')
    op.drop_table('anamnesis_answer_history')
    op.drop_index(op.f('ix_wellbeing_assessments_patient_id'), table_name='wellbeing_assessments')
    op.drop_table('wellbeing_assessments')
    op.drop_index(op.f('ix_risk_assessments_patient_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_patient_medications_patient_id'), table_name='patient_medications')
    op.drop_table('patient_medications')
    op.drop_index(op.f('ix_monitoring_plan_items_patient_id'), table_name='monitoring_plan_items')
    op.drop_table('monitoring_plan_items')
    op.drop_index(op.f('ix_health_goals_patient_id'), table_name='health_goals')
    op.drop_table('health_goals')
    op.drop_index(op.f('ix_follow_ups_patient_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_chat_threads_patient_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_care_pathways_patient_id'), table_name='care_pathways')
    op.drop_table('care_pathways')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_anamnesis_answers_patient_id'), table_name='anamnesis_answers')
    op.drop_table('anamnesis_answers')
    op.drop_table('patients')
    op.drop_table('pathway_template_steps')
    op.drop_table('doctors')
    op.drop_table('users')
    op.drop_table('pathway_templates')
    op.drop_table('anamnesis_questions')
    # ### end Alembic commands ###
